### ISSUE TITLE
build and install wsktool raises problem.

### ISSUE THREAD

**Issue by lzbj** [openwhisk/wskdeploy#10]
With current codebase, when I try make build, the go will complain "fatal: repository 'https://github.com/openwhisk/go-whisk/' not found", because currently the repo doesn't exists.
So the import will fail.

If I change the package import source code to github.com/openwhisk/openwhisk/tools/cli/go-whisk/whisk, the go will complain that
" Installing dependencies
$GOPATH/src/github.com/openwhisk/openwhisk/tools/cli/go-whisk/whisk/client.go:31:5: local import "../wski18n" in non-local package"

**Comment by lzbj** [comment]
It seems the reason is here:https://golang.org/cmd/go/#hdr-Relative_import_paths

**Comment by paulcastro** [comment]
Will close for now given temporary location of go-whisk repo.  There is open issue in the core OpenWhisk to look at setting this up.

See: https://github.com/openwhisk/openwhisk/issues/1480
