### ISSUE TITLE
Add parser for manifest.yml and integrate with  servicedeployer.

### ISSUE THREAD

**Issue by daisy-ycguo** [openwhisk/wskdeploy#18]
We want a parser to support the elements in the manifest files of testcase1.
I'm going to make the following changes:
- utils/manifest.go will be added for manifest_full.yaml parser.
- tests/manifest_test.go will be added accordingly.
- remove deployment.go and test code according.
- Integrate manifest.go with deployerService.
- Add corresponding test cases for the integration.
- Refactor and change existing code if necessary.

**Comment by lzbj** [comment]
Done.
