### ISSUE TITLE
Is the action needs to be hard coded in the sample manifesto yaml?

### ISSUE THREAD

**Issue by lzbj** [openwhisk/wskdeploy#23]
Currently the manifest_full.yaml the action hello is hard coded, which makes parser a little bit confused, so the better action name would be action, and put the action name as a property?

Another issue, do we need to consider some web contents, I read the spec, it seems some action or whisk entities maybe on the web?

**Comment by lzbj** [comment]
Daisy could you take a look?

**Comment by daisy-ycguo** [comment]
@lzbj action name is not hard coded. If you set the type as a map, you can get the action names as Keys.

As to your second question, I think we can save the request as our future target. In the first and two iteration, we only consider the local files, but we should support both relative path and absolute path.

**Comment by daisy-ycguo** [comment]
The issue has been addressed in dev meeting. We finally agreed to not use arrays in yaml files. 
I closed it.
