### ISSUE TITLE
Create an apiClient that integrates with the go-whisk package

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/wskdeploy#4]
The OpenWhisk API has an existing Go package go-whisk that implements the OpenWhisk REST API.  It is designed to be re-used by other applications.  We should integrate our tool with this package to handle the network calls to an OpenWhisk instance.

go-whisk will provide us with:
- A REST API implementation
- A framework for adding i18n to our code

**Comment by rabbah** [comment]
A good motivation to pull the CLI out of the main repo? @csantanapr FYI

**Comment by csantanapr** [comment]
@paulcastro feel free to work on putting go-whisk on it's own repo, this way you can added as a dependency for wsktool. then wsk cli and wsktool can leverage the same library.

CC @mdeuser

**Comment by mdeuser** [comment]
Some extra go-whisk/go-whisk-cli decoupling may be required to facilitate this work.  I think some utility functions may be shared...

**Comment by paulcastro** [comment]
This has been addressed by new deployer architecture, will close.
