### ISSUE TITLE
[WIP]Add basic support of deployment.yml

### ISSUE THREAD

**Issue by daisy-ycguo** [openwhisk/wskdeploy#45]
We need to start supporting deployment file. According to the Specification, a Deployment file contains configuration information, e.g.
- input parameters
- authorization credentials
- namespaces

and so on.

There is a simple Deployment file in tests/testcases/triggerrule, with namespaces of application and packages, authorization credential of OW, and input parameters to rule. We can start the support of deployment file from this basic case.

**Comment by lzbj** [comment]
Daisy is discussing and confirming with Matt about the sample deployment yaml definition and usage. The code implementation will follow that.
