### ISSUE TITLE
"go build" fails; missing "github.com/cloudfoundry/jibber_jabber"

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/wskdeploy#69]
Following the README, the "go get" command did automatically pull the go CLI, but did not get these new Cloud Foundry dependencies.  This message is shown on command line building the development branch:

<img width="896" alt="screen shot 2017-01-02 at 10 01 03 pm" src="https://cloud.githubusercontent.com/assets/7816715/21599747/4271638e-d137-11e6-8d59-c607a43a6a23.png">

**Comment by mrutkows** [comment]
What is this package called "nicksnyder" that sounds rather dubious for us to include?  What is it used for and is this an approved package with known license?

**Comment by lzbj** [comment]
We need run "go get -t -d ./..." before run the go build, I'll submit a pr to the readme to fix this issue.

**Comment by mrutkows** [comment]
Shouldn't updating "godeps" fix this?  Also, I am more concerned that we are pulling in more non-standard libraries that have questionable licenses. Apache will not like this if we want to leave incubator.

**Comment by mrutkows** [comment]
it is also the i18n lib. as well

**Comment by lzbj** [comment]
Close this one as we have issue #73, #74 to track it.
