### ISSUE TITLE
Update godeps to include 2 libraries (i18n, jibber_jabber)

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/wskdeploy#74]
Of course we can always use "go get" flags to assure that the tool will automatically "pull" all dependent libs. that it finds; however, we should also make these library import (dependencies) explicit as well in our "godeps" file (i.e., https://github.com/openwhisk/wskdeploy/blob/master/Godeps/Godeps.json).

This SHOULD allow people to simply use "go get" with no flags as intended (for simplicity).

**Comment by lzbj** [comment]
Correct, it's been a best practice once you add one package or module, run the `godep save` command to update the dependency file. Apparently we didn't do that for a while. Will submit a pr to update the file and update the README.md to tell user to install and use godep tool.

**Comment by mrutkows** [comment]
@mdeuser fyi, we are adding to godeps
